# Generated by Django 3.1.3 on 2020-11-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_vendedor', models.IntegerField()),
                ('usuario', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.producto')),
                ('cod_vendedor_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_vendedor_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.vendedor'),
        ),
    ]
