# Generated by Django 3.1.3 on 2020-11-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201112_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='cod_vendedor',
        ),
    ]
