# Generated by Django 3.1.3 on 2020-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_vendedor_cod_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cod_vendedor',
            field=models.IntegerField(default=0),
        ),
    ]
