# Generated by Django 3.1.3 on 2020-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_vendedor_cod_vendedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.IntegerField(default=0),
        ),
    ]
